
import pandas as pd
import numpy as np
import os
from datetime import datetime

class TraderReporter:
    """
    Generates professional performance reports from mock or real trade data.
    """
    
    def __init__(self, report_dir="reports"):
        self.report_dir = report_dir
        os.makedirs(self.report_dir, exist_ok=True)
        
    def generate_report(self, df_history, model_name="NeuroTrader", role="General"):
        """
        Creates a Markdown report from trade history DataFrame.
        """
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        filename = f"{self.report_dir}/REPORT_{role}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
        
        # 1. Metrics Calculation
        initial_equity = df_history['equity'].iloc[0]
        final_equity = df_history['equity'].iloc[-1]
        pnl_abs = final_equity - initial_equity
        pnl_pct = (pnl_abs / initial_equity) * 100
        
        # Max Drawdown
        peak = df_history['equity'].cummax()
        dd = (df_history['equity'] - peak) / peak * 100
        max_dd = dd.min()
        
        # Trade Analysis (Approximate from equity jumps if no trade log, 
        # but better if we have 'trade' column)
        # Assuming df_history has 'position'
        df_history['is_trade'] = df_history['position'] != df_history['position'].shift()
        total_trades = df_history['is_trade'].sum()
        
        # 2. Generate Content
        content = f"""# 📊 NeuroTrader Performance Brief
**Date:** {timestamp}
**Model:** {model_name}
**Role:** {role.upper()}

---

## 💰 Executive Summary
| Metric | Value |
| :--- | :--- |
| **Net Profit** | `${pnl_abs:,.2f}` |
| **Return** | `{pnl_pct:,.2f}%` |
| **Max Drawdown** | `{max_dd:.2f}%` |
| **Total Activity** | `{total_trades}` adjustments |
| **Final Equity** | `${final_equity:,.2f}` |

## 📈 Performance Analysis
- **Profitability**: The model generated a return of {pnl_pct:.1f}%.
- **Risk**: The maximum drawdown encountered was {max_dd:.2f}%.
"""

        # Add Exposure Analysis
        exposure_pct = (df_history['position'] != 0).mean() * 100
        content += f"""
## 🛡️ Risk & Exposure
- **Market Exposure**: {exposure_pct:.1f}% of the time in market.
- **Cash Position**: {100 - exposure_pct:.1f}% of the time.
"""

        # Recommendations
        rec = "None"
        if pnl_pct > 0 and max_dd > -5:
            rec = "✅ **Approve for Live**: Performance is consistent with low risk."
        elif max_dd < -20:
            rec = "⚠️ **Critical Review**: Drawdown exceeds safety limits. Reduce leverage."
        else:
            rec = "🔄 **Monitor**: Performance is acceptable but needs more observation."
            
        content += f"""
## 🤖 AI Recommendation
{rec}

---
*Generated by NeuroTrader V3 Reporter Skill*
"""
        
        # Save
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
            
        print(f"Report Generated: {filename}")
        return filename

if __name__ == "__main__":
    # Test
    data = {
        'equity': [10000 + i + np.random.randn()*10 for i in range(100)],
        'position': [0]*20 + [1]*50 + [0]*30
    }
    df = pd.DataFrame(data)
    reporter = TraderReporter()
    reporter.generate_report(df, role="TESTER")
